name: internship_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  animated_bottom_navigation_bar: ^1.2.0
  http: ^1.1.0
  loading_animation_widget: ^1.2.0+4
  cached_network_image: ^3.2.3
  animated_text_kit: ^4.2.2
  easy_splash_screen: ^1.0.4
  flutter_spinkit: ^5.2.0
  google_fonts: ^5.1.0
  flutter_carousel_slider: ^1.1.0
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
